'use strict';

const ServerConfig = {
    MIN_FPS: 8,
    STARTING_FPS: 10,
    MAX_FPS: 60,
    PLAYER_STARTING_LENGTH: 4,
    SPAWN_TURN_LEEWAY: 10,
    DEFAULT_STARTING_BOTS: 0,
    MAX_BOTS: 20,
    BOT_CHANGE_DIRECTION_PERCENT: 0.1,
    FOOD: {
        DEFAULT_AMOUNT: 25,
        NORMAL: {
            TYPE: 'NORMAL',
            COLOR: 'red',
            POINTS: 1,
            GROWTH: 1,
        },
        SUPER: {
            TYPE: 'SUPER',
            COLOR: 'green',
            POINTS: 5,
            GROWTH: 5,
            SPAWN_RATE: 0.4,
        },
        ROTTEN: {
            TYPE: 'ROTTEN',
            COLOR: 'brown',
            POINTS: -5,
            GROWTH: -5,
            SPAWN_RATE: 0.1,
        },
        GOLDEN: {
            TYPE: 'GOLDEN',
            COLOR: 'yellow',
            POINTS: 25,
            GROWTH: 25,
            SPAWN_RATE: 0.02,
        },
        SWAP: {
            TYPE: 'SWAP',
            COLOR: 'blue',
            POINTS: 1,
            GROWTH: 1,
            SPAWN_RATE: 0.01,
        },
        INCREASE_SPEED: {
            TYPE: 'INCREASE_SPEED',
            COLOR: 'purple',
            POINTS: 17,
            GROWTH: 17,
            SPAWN_RATE: 0.05,
        },
    },
    IO: {
        DEFAULT_CONNECTION: 'connection',
        INCOMING: {
            BOT_CHANGE: 'bot change',
            COLOR_CHANGE: 'player changed color',
            FOOD_CHANGE: 'food change',
            SPEED_CHANGE: 'speed change',
            START_LENGTH_CHANGE: 'start length change',
            JOIN_GAME: 'join game',
            SPECTATE_GAME: 'spectate game',
            CLEAR_UPLOADED_BACKGROUND_IMAGE: 'clear uploaded background image',
            BACKGROUND_IMAGE_UPLOAD: 'background image upload',
            CLEAR_UPLOADED_IMAGE: 'clear uploaded image',
            PLAYER_COUNT: 'player count',
            IMAGE_UPLOAD: 'image upload',
            NEW_PLAYER: 'new player',
            NAME_CHANGE: 'player changed name',
            KEY_DOWN: 'key down',
            CANVAS_CLICKED: 'canvas clicked',
            DISCONNECT: 'disconnect',
        },
        OUTGOING: {
            NEW_STATE: 'game update',
            NEW_PLAYER_INFO: 'new player info',
            NEW_BACKGROUND_IMAGE: 'new background image',
            BOARD_INFO: 'board info',
            START_VIDEO: 'start videos',
            START_GAME: 'start game',
            PLAYER_COUNT: 'player count',
            NOTIFICATION: {
                GENERAL: 'general notification',
                FOOD_COLLECTED: 'food collected',
                KILL: 'kill notification',
                KILLED_EACH_OTHER: 'killed each other notification',
                RAN_INTO_WALL: 'ran into wall notification',
                SUICIDE: 'suicide notification',
                YOU_DIED: 'you died',
                YOU_MADE_A_KILL: 'you made a kill',
            },
        },
    },
    SNAKES: {
        COLORS: ['#FF6633', '#FFB399', '#FF33FF', '#FFFF99', '#00B3E6',
            '#E6B333', '#3366E6', '#B34D4D',
            '#6680B3',
            '#FF99E6', '#CCFF1A', '#FF1A66', '#E6331A', '#33FFCC',
            '#B366CC', '#4D8000', '#B33300', '#CC80CC',
            '#66664D', '#991AFF', '#E666FF', '#4DB3FF', '#1AB399',
            '#E666B3', '#CC9999',
            '#4D8066', '#809980',
            '#FF3380', '#4D80CC', '#9900B3',
            '#E64D66', '#4DB380', '#FF4D4D', '#6666FF',
            '#ffff00',
            '#00ffff',
            '#ff3399',
            '#9900ff',
            '#ff6600',
            '#512DA8',
            '#FF5722',
            '#F44336',
            '#536DFE',
            '#000000',
            '#FFFFFF',
            '#e6194b',
            '#3cb44b',
            '#ffe119',
            '#4363d8',
            '#911eb4',
            '#46f0f0',
            '#f032e6',
            '#fabebe',
            '#008080',
            '#9a6324',
            '#fffac8',
            '#800000',
            '#808000',
            '#000075',
            '#808080',

        ],
    },
    INCREMENT_CHANGE: {
        INCREASE: 'increase',
        DECREASE: 'decrease',
        RESET: 'reset',
    },
};

module.exports = ServerConfig;